version: '3.7'
services:

#mysql datatbase for the site
  db:
    image: mysql:5.7 #msql image from dockerhub
    volumes: #docker volume for data persistency
      - db_data:/var/lib/mysql
    restart: always #restart the container in any case it stops
    environment: #evironmnetal variable to pass in the credentials
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password

  #wordress app
  wordpress:
    depends_on: #start the db container before starting this container
      - db
    image:  wordpress:latest #wordpress image from dockerhub
    ports:
      - 8000:80
    restart: always #restart the container in any case it stops
    environment: #evironmnetal variable to pass in the credentials
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_mysql_username
      WORDPRESS_DB_PASSWORD: your_mysql_password
      WORDPRESS_DB_NAME: your_mysql_database_name

#docker volume for data persister across all containers
volumes:
  db_data:
    driver: local
  